import type { Fiche } from "@/types/fiche";

const MOCK_FICHES: Fiche[] = [
  {
    id: "1",
    client: { name: "Amélie Laurent", phone: "06 11 24 38 51", email: "amelie.laurent@example.com" },
    status: "NEW",
    advisor: "S. Martin",
    createdAt: "2026-04-05T09:15:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Responsabilité civile", "Bris de glace", "Vol"],
      prime: 620,
    },
  },
  {
    id: "2",
    client: { name: "Karim Benali", phone: "06 22 35 47 62", email: "karim.benali@example.com" },
    status: "ASSIGNED",
    advisor: "L. Benali",
    createdAt: "2026-04-04T10:30:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Dégât des eaux", "Incendie", "Catastrophes naturelles"],
      prime: 410,
    },
  },
  {
    id: "3",
    client: { name: "Claire Dupont", phone: "06 33 46 58 73", email: "claire.dupont@example.com" },
    status: "IN_PROGRESS",
    advisor: "C. Dupont",
    createdAt: "2026-04-03T14:10:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Protection juridique", "Défense recours", "Dommages tiers"],
      prime: 980,
    },
  },
  {
    id: "4",
    client: { name: "Marc Bernard", phone: "06 44 57 68 84", email: "marc.bernard@example.com" },
    status: "CLOSED",
    advisor: "M. Bernard",
    createdAt: "2026-04-02T08:45:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Responsabilité civile", "Assistance 0 km", "Vol"],
      prime: 675,
    },
  },
  {
    id: "5",
    client: { name: "Nadia Hamadi", phone: "06 55 68 79 95", email: "nadia.hamadi@example.com" },
    status: "NEW",
    advisor: "S. Martin",
    createdAt: "2026-04-01T11:25:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Incendie", "Dégât des eaux", "Vol"],
      prime: 455,
    },
  },
  {
    id: "6",
    client: { name: "Thomas Leroy", phone: "06 66 79 80 16", email: "thomas.leroy@example.com" },
    status: "ASSIGNED",
    advisor: "L. Benali",
    createdAt: "2026-03-31T15:05:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Protection juridique", "Responsabilité civile professionnelle"],
      prime: 1120,
    },
  },
  {
    id: "7",
    client: { name: "Sophie Martin", phone: "06 77 80 91 27", email: "sophie.martin@example.com" },
    status: "IN_PROGRESS",
    advisor: "C. Dupont",
    createdAt: "2026-03-30T09:40:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Vol", "Bris de glace", "Tous risques"],
      prime: 740,
    },
  },
  {
    id: "8",
    client: { name: "Yasmine Costa", phone: "06 88 91 02 38", email: "yasmine.costa@example.com" },
    status: "CLOSED",
    advisor: "M. Bernard",
    createdAt: "2026-03-29T13:20:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Incendie", "Vol", "Responsabilité civile vie privée"],
      prime: 390,
    },
  },
  {
    id: "9",
    client: { name: "Julien Moreau", phone: "06 99 02 13 49", email: "julien.moreau@example.com" },
    status: "NEW",
    advisor: "S. Martin",
    createdAt: "2026-03-28T10:55:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Dommages tiers", "Défense recours", "Protection juridique"],
      prime: 890,
    },
  },
  {
    id: "10",
    client: { name: "Inès Pereira", phone: "06 10 13 24 50", email: "ines.pereira@example.com" },
    status: "ASSIGNED",
    advisor: "L. Benali",
    createdAt: "2026-03-27T16:00:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Responsabilité civile", "Protection du conducteur", "Vol"],
      prime: 605,
    },
  },
  {
    id: "11",
    client: { name: "Romain Petit", phone: "06 21 24 35 61", email: "romain.petit@example.com" },
    status: "IN_PROGRESS",
    advisor: "C. Dupont",
    createdAt: "2026-03-26T09:10:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Dégât des eaux", "Catastrophes naturelles", "Responsabilité civile"],
      prime: 430,
    },
  },
  {
    id: "12",
    client: { name: "Élodie Garcia", phone: "06 32 35 46 72", email: "elodie.garcia@example.com" },
    status: "CLOSED",
    advisor: "M. Bernard",
    createdAt: "2026-03-25T14:35:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Défense recours", "Protection juridique", "Assistance"],
      prime: 1010,
    },
  },
  {
    id: "13",
    client: { name: "Hugo Robert", phone: "06 43 46 57 83", email: "hugo.robert@example.com" },
    status: "NEW",
    advisor: "S. Martin",
    createdAt: "2026-03-24T08:50:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Vol", "Bris de glace", "Assistance"],
      prime: 660,
    },
  },
  {
    id: "14",
    client: { name: "Camille Faure", phone: "06 54 57 68 94", email: "camille.faure@example.com" },
    status: "ASSIGNED",
    advisor: "L. Benali",
    createdAt: "2026-03-23T11:15:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Incendie", "Dégât des eaux", "Vol"],
      prime: 445,
    },
  },
  {
    id: "15",
    client: { name: "Antoine Legrand", phone: "06 65 68 79 05", email: "antoine.legrand@example.com" },
    status: "IN_PROGRESS",
    advisor: "C. Dupont",
    createdAt: "2026-03-22T15:45:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Responsabilité civile professionnelle", "Protection juridique"],
      prime: 1240,
    },
  },
  {
    id: "16",
    client: { name: "Sarah Diallo", phone: "06 76 79 80 16", email: "sarah.diallo@example.com" },
    status: "CLOSED",
    advisor: "M. Bernard",
    createdAt: "2026-03-21T10:20:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Tous risques", "Vol", "Assistance 0 km"],
      prime: 790,
    },
  },
  {
    id: "17",
    client: { name: "Mohamed Khelifi", phone: "06 87 80 91 27", email: "mohamed.khelifi@example.com" },
    status: "NEW",
    advisor: "S. Martin",
    createdAt: "2026-03-20T13:05:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Incendie", "Catastrophes naturelles", "Responsabilité civile"],
      prime: 405,
    },
  },
  {
    id: "18",
    client: { name: "Lucie Bernard", phone: "06 98 91 02 38", email: "lucie.bernard@example.com" },
    status: "ASSIGNED",
    advisor: "L. Benali",
    createdAt: "2026-03-19T09:55:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Défense recours", "Dommages tiers", "Protection juridique"],
      prime: 945,
    },
  },
  {
    id: "19",
    client: { name: "Aline Rousseau", phone: "06 09 12 23 49", email: "aline.rousseau@example.com" },
    status: "IN_PROGRESS",
    advisor: "C. Dupont",
    createdAt: "2026-03-18T16:40:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Responsabilité civile", "Bris de glace", "Vol"],
      prime: 630,
    },
  },
  {
    id: "20",
    client: { name: "Nicolas Weber", phone: "06 10 23 34 50", email: "nicolas.weber@example.com" },
    status: "CLOSED",
    advisor: "M. Bernard",
    createdAt: "2026-03-17T12:30:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Dégât des eaux", "Vol", "Incendie"],
      prime: 465,
    },
  },
  {
    id: "21",
    client: { name: "Fanny Girard", phone: "06 21 34 45 61", email: "fanny.girard@example.com" },
    status: "NEW",
    advisor: "S. Martin",
    createdAt: "2026-03-16T09:00:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Protection juridique", "Dommages tiers"],
      prime: 870,
    },
  },
  {
    id: "22",
    client: { name: "Baptiste Colin", phone: "06 32 45 56 72", email: "baptiste.colin@example.com" },
    status: "ASSIGNED",
    advisor: "L. Benali",
    createdAt: "2026-03-15T14:15:00.000Z",
    product: {
      type: "AUTO",
      garanties: ["Tous risques", "Assistance 0 km", "Vol"],
      prime: 715,
    },
  },
  {
    id: "23",
    client: { name: "Mélanie Arnaud", phone: "06 43 56 67 83", email: "melanie.arnaud@example.com" },
    status: "IN_PROGRESS",
    advisor: "C. Dupont",
    createdAt: "2026-03-14T11:35:00.000Z",
    product: {
      type: "MRH",
      garanties: ["Incendie", "Dégât des eaux", "Responsabilité civile"],
      prime: 420,
    },
  },
  {
    id: "24",
    client: { name: "Olivier Mercier", phone: "06 54 67 78 94", email: "olivier.mercier@example.com" },
    status: "CLOSED",
    advisor: "M. Bernard",
    createdAt: "2026-03-13T10:05:00.000Z",
    product: {
      type: "RCPRO",
      garanties: ["Responsabilité civile professionnelle", "Défense recours", "Assistance"],
      prime: 1180,
    },
  },
];

export default MOCK_FICHES;
